Mutation:
  type: object
  config:
    fields:
      createProduct:
        type: "Product!"
        args:
          name:
            type: "String!"
          price:
            type: "Float!"
        resolve: "@=resolver('App\\GraphQL\\Resolver\\ProductMutationResolver::createProduct', [args])"
