Mutation:
  type: object
  config:
    description: "The GraphQL Mutation Interface"
    fields:
      addition:
        type: Int
        args:
          number:
            type: Int
        resolve: '@=mutation("App\\Resolver\\CalcMutation::addition", args["number"])'

      product_add:
        type: Product
        args:
          product:
            type: ProductInput
        resolve: '@=mutation("App\\Resolver\\ProductMutation::add", args["product"])'

      product_update:
        type: Product
        args:
          product_id:
            type: Int
          new_product:
            type: ProductInput
        resolve: '@=mutation("App\\Resolver\\ProductMutation::update", args["product_id"], args["new_product"])'

      product_delete:
        type: Boolean
        args:
          product_id:
            type: Int
        resolve: '@=mutation("App\\Resolver\\ProductMutation::delete", args["product_id"])'